
import type { Category, Product } from '@shared/schema';

export const mockCategories: Category[] = [
  {
    id: "5db60edb-5e2e-4811-adb0-385dfdf1694e",
    nameEn: "Watches",
    nameAr: "ساعات",
    slug: "watches",
    image: "/stock_images/luxury_gold_watch_on_f521e06a.jpg",
  },
  {
    id: "8a9c7b1d-2e4f-5a6b-9c8d-1e2f3a4b5c6d",
    nameEn: "Accessories",
    nameAr: "إكسسوارات",
    slug: "accessories",
    image: "/stock_images/elegant_jewelry_acce_2b234ecd.jpg",
  },
  {
    id: "7f8e9d0c-1b2a-3c4d-5e6f-7a8b9c0d1e2f",
    nameEn: "Makeup",
    nameAr: "مكياج",
    slug: "makeup",
    image: "/stock_images/luxury_makeup_cosmet_ef2662b8.jpg",
  },
  {
    id: "6e7d8c9b-0a1b-2c3d-4e5f-6a7b8c9d0e1f",
    nameEn: "Gifts",
    nameAr: "هدايا",
    slug: "gifts",
    image: "/stock_images/luxury_perfume_gift__548a5b12.jpg",
  },
];

export const mockProducts: Product[] = [
  {
    id: "cefc4bec-1688-4a42-9646-9c51469a59ba",
    categoryId: "5db60edb-5e2e-4811-adb0-385dfdf1694e",
    nameEn: "Classic Gold Watch",
    nameAr: "ساعة ذهبية كلاسيكية",
    descriptionEn: "Elegant gold-plated timepiece with precision Swiss movement. Features a classic round dial with Roman numerals and genuine leather strap. Water-resistant up to 50 meters. Perfect for both formal and casual occasions.",
    descriptionAr: "ساعة أنيقة مطلية بالذهب مع حركة سويسرية دقيقة. تتميز بقرص دائري كلاسيكي مع أرقام رومانية وحزام جلد أصلي. مقاومة للماء حتى 50 متر. مثالية للمناسبات الرسمية والعادية.",
    price: "899.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_gold_watch_on_f521e06a.jpg",
      "/stock_images/luxury_gold_watch_on_173d21b2.jpg",
      "/stock_images/luxury_gold_watch_on_8dadeeca.jpg",
    ],
    featured: 1,
    slug: "classic-gold-watch",
  },
  {
    id: "d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a",
    categoryId: "5db60edb-5e2e-4811-adb0-385dfdf1694e",
    nameEn: "Luxury Chronograph Watch",
    nameAr: "ساعة كرونوغراف فاخرة",
    descriptionEn: "Premium chronograph watch with stainless steel case and sapphire crystal. Features three subdials and a date display. Automatic movement with 48-hour power reserve. Ideal for the distinguished gentleman.",
    descriptionAr: "ساعة كرونوغراف فاخرة مع علبة من الفولاذ المقاوم للصدأ وكريستال الياقوت. تتميز بثلاثة أقراص فرعية وعرض التاريخ. حركة أوتوماتيكية مع احتياطي طاقة 48 ساعة. مثالية للرجل المميز.",
    price: "1299.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_gold_watch_on_173d21b2.jpg",
      "/stock_images/luxury_gold_watch_on_f521e06a.jpg",
    ],
    featured: 0,
    slug: "luxury-chronograph-watch",
  },
  {
    id: "e2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a7b",
    categoryId: "8a9c7b1d-2e4f-5a6b-9c8d-1e2f3a4b5c6d",
    nameEn: "Diamond Pendant Necklace",
    nameAr: "قلادة مع دلاية ألماس",
    descriptionEn: "Exquisite 18K white gold necklace featuring a brilliant-cut diamond pendant. Delicate chain design with secure clasp. Comes with certificate of authenticity. A timeless piece of elegance.",
    descriptionAr: "قلادة رائعة من الذهب الأبيض عيار 18 قيراط تتميز بدلاية ألماس مقطوعة ببراعة. تصميم سلسلة رقيق مع قفل آمن. يأتي مع شهادة أصالة. قطعة أناقة خالدة.",
    price: "1599.00",
    currency: "USD",
    images: [
      "/stock_images/elegant_jewelry_acce_2b234ecd.jpg",
      "/stock_images/elegant_jewelry_acce_ab2c1b10.jpg",
    ],
    featured: 1,
    slug: "diamond-pendant-necklace",
  },
  {
    id: "f3a4b5c6-d7e8-9f0a-1b2c-3d4e5f6a7b8c",
    categoryId: "8a9c7b1d-2e4f-5a6b-9c8d-1e2f3a4b5c6d",
    nameEn: "Pearl Drop Earrings",
    nameAr: "أقراط اللؤلؤ المتدلية",
    descriptionEn: "Sophisticated freshwater pearl earrings with sterling silver settings. Classic drop design that complements any outfit. Hypoallergenic and perfect for sensitive ears. Includes elegant gift box.",
    descriptionAr: "أقراط أنيقة من اللؤلؤ الطبيعي مع إطارات من الفضة الإسترلينية. تصميم متدلي كلاسيكي يكمل أي ملابس. مضاد للحساسية ومثالي للأذن الحساسة. يشمل صندوق هدايا أنيق.",
    price: "399.00",
    currency: "USD",
    images: [
      "/stock_images/elegant_jewelry_acce_ab2c1b10.jpg",
      "/stock_images/elegant_jewelry_acce_74bb331e.jpg",
    ],
    featured: 0,
    slug: "pearl-drop-earrings",
  },
  {
    id: "a4b5c6d7-e8f9-0a1b-2c3d-4e5f6a7b8c9d",
    categoryId: "8a9c7b1d-2e4f-5a6b-9c8d-1e2f3a4b5c6d",
    nameEn: "Gold Bracelet Set",
    nameAr: "طقم أساور ذهبية",
    descriptionEn: "Elegant set of three gold-plated bangles with intricate detailing. Stackable design for versatile styling. Adjustable sizing for comfortable wear. Perfect gift for any occasion.",
    descriptionAr: "طقم أنيق من ثلاثة أساور مطلية بالذهب مع تفاصيل معقدة. تصميم قابل للتكديس لتنسيق متعدد الاستخدامات. مقاس قابل للتعديل لارتداء مريح. هدية مثالية لأي مناسبة.",
    price: "499.00",
    currency: "USD",
    images: [
      "/stock_images/elegant_jewelry_acce_74bb331e.jpg",
      "/stock_images/elegant_jewelry_acce_2b234ecd.jpg",
    ],
    featured: 0,
    slug: "gold-bracelet-set",
  },
  {
    id: "b5c6d7e8-f9a0-1b2c-3d4e-5f6a7b8c9d0e",
    categoryId: "7f8e9d0c-1b2a-3c4d-5e6f-7a8b9c0d1e2f",
    nameEn: "Luxury Lipstick Collection",
    nameAr: "مجموعة أحمر شفاه فاخرة",
    descriptionEn: "Premium lipstick set featuring 5 gorgeous shades from nude to bold red. Long-lasting, hydrating formula enriched with vitamin E. Elegant gold packaging. Cruelty-free and paraben-free.",
    descriptionAr: "طقم أحمر شفاه فاخر يضم 5 درجات رائعة من اللون الطبيعي إلى الأحمر الجريء. تركيبة طويلة الأمد ومرطبة غنية بفيتامين E. تغليف ذهبي أنيق. خالي من القسوة والبارابين.",
    price: "149.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_makeup_cosmet_ef2662b8.jpg",
      "/stock_images/luxury_makeup_cosmet_435574f1.jpg",
    ],
    featured: 1,
    slug: "luxury-lipstick-collection",
  },
  {
    id: "c6d7e8f9-a0b1-2c3d-4e5f-6a7b8c9d0e1f",
    categoryId: "7f8e9d0c-1b2a-3c4d-5e6f-7a8b9c0d1e2f",
    nameEn: "Professional Eyeshadow Palette",
    nameAr: "لوحة ظلال عيون احترافية",
    descriptionEn: "Stunning eyeshadow palette with 12 highly pigmented shades. Mix of matte and shimmer finishes. Blendable formula for professional results. Includes dual-ended brush and mirror.",
    descriptionAr: "لوحة ظلال عيون مذهلة مع 12 درجة عالية الصبغة. مزيج من التشطيبات المطفية واللامعة. تركيبة قابلة للمزج لنتائج احترافية. تشمل فرشاة مزدوجة الطرف ومرآة.",
    price: "89.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_makeup_cosmet_435574f1.jpg",
      "/stock_images/luxury_makeup_cosmet_38f4e6ef.jpg",
    ],
    featured: 0,
    slug: "professional-eyeshadow-palette",
  },
  {
    id: "d7e8f9a0-b1c2-3d4e-5f6a-7b8c9d0e1f2a",
    categoryId: "7f8e9d0c-1b2a-3c4d-5e6f-7a8b9c0d1e2f",
    nameEn: "Luxury Makeup Brush Set",
    nameAr: "طقم فرش مكياج فاخر",
    descriptionEn: "Complete 10-piece brush set with synthetic bristles. Includes face, eye, and lip brushes in elegant rose gold handles. Comes with premium leather case. Perfect for travel and daily use.",
    descriptionAr: "طقم فرش كامل من 10 قطع مع شعيرات صناعية. يشمل فرش الوجه والعين والشفاه مع مقابض ذهبية وردية أنيقة. يأتي مع حافظة جلدية فاخرة. مثالي للسفر والاستخدام اليومي.",
    price: "199.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_makeup_cosmet_38f4e6ef.jpg",
      "/stock_images/luxury_makeup_cosmet_ef2662b8.jpg",
    ],
    featured: 0,
    slug: "luxury-makeup-brush-set",
  },
  {
    id: "e8f9a0b1-c2d3-4e5f-6a7b-8c9d0e1f2a3b",
    categoryId: "6e7d8c9b-0a1b-2c3d-4e5f-6a7b8c9d0e1f",
    nameEn: "Premium Perfume Gift Set",
    nameAr: "طقم عطر فاخر للهدايا",
    descriptionEn: "Luxurious perfume gift set featuring our signature fragrance in 100ml bottle plus travel-size 15ml. Notes of jasmine, vanilla, and sandalwood. Presented in elegant gift packaging.",
    descriptionAr: "طقم عطر فاخر للهدايا يضم عطرنا المميز في زجاجة 100 مل بالإضافة إلى حجم السفر 15 مل. روائح الياسمين والفانيليا وخشب الصندل. يقدم في تغليف هدايا أنيق.",
    price: "299.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_perfume_gift__548a5b12.jpg",
      "/stock_images/luxury_perfume_gift__aa85a4a9.jpg",
    ],
    featured: 1,
    slug: "premium-perfume-gift-set",
  },
  {
    id: "f9a0b1c2-d3e4-5f6a-7b8c-9d0e1f2a3b4c",
    categoryId: "6e7d8c9b-0a1b-2c3d-4e5f-6a7b8c9d0e1f",
    nameEn: "Deluxe Fragrance Collection",
    nameAr: "مجموعة عطور ديلوكس",
    descriptionEn: "Exclusive collection of 3 miniature perfumes in travel-friendly sizes. Features floral, woody, and oriental scents. Perfect gift for fragrance lovers. Premium glass bottles with gold accents.",
    descriptionAr: "مجموعة حصرية من 3 عطور صغيرة بأحجام مناسبة للسفر. تضم روائح زهرية وخشبية وشرقية. هدية مثالية لعشاق العطور. زجاجات زجاجية فاخرة مع لمسات ذهبية.",
    price: "179.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_perfume_gift__aa85a4a9.jpg",
      "/stock_images/luxury_perfume_gift__94fbf062.jpg",
    ],
    featured: 0,
    slug: "deluxe-fragrance-collection",
  },
  {
    id: "a0b1c2d3-e4f5-6a7b-8c9d-0e1f2a3b4c5d",
    categoryId: "6e7d8c9b-0a1b-2c3d-4e5f-6a7b8c9d0e1f",
    nameEn: "Elegant Perfume Bottle",
    nameAr: "زجاجة عطر أنيقة",
    descriptionEn: "Sophisticated eau de parfum in crystal-cut bottle. Long-lasting floral and citrus notes perfect for day and evening wear. Makes a stunning gift. 75ml premium fragrance.",
    descriptionAr: "عطر فاخر في زجاجة مقطوعة بالكريستال. روائح زهرية وحمضيات طويلة الأمد مثالية للنهار والمساء. يقدم هدية مذهلة. عطر فاخر 75 مل.",
    price: "249.00",
    currency: "USD",
    images: [
      "/stock_images/luxury_perfume_gift__94fbf062.jpg",
      "/stock_images/luxury_perfume_gift__548a5b12.jpg",
    ],
    featured: 0,
    slug: "elegant-perfume-bottle",
  },
];
