import type { Category, Product } from '@shared/schema';

export const categories: Category[] = [
  {
    id: '1',
    nameEn: 'Watches',
    nameAr: 'ساعات',
    slug: 'watches',
    image: '/images/luxury_gold_watch_on_f521e06a.jpg',
  },
  {
    id: '2',
    nameEn: 'Accessories',
    nameAr: 'إكسسوارات',
    slug: 'accessories',
    image: '/images/elegant_jewelry_acce_2b234ecd.jpg',
  },
  {
    id: '3',
    nameEn: 'Makeup',
    nameAr: 'مكياج',
    slug: 'makeup',
    image: '/images/luxury_makeup_cosmet_ef2662b8.jpg',
  },
  {
    id: '4',
    nameEn: 'Gifts',
    nameAr: 'هدايا',
    slug: 'gifts',
    image: '/images/luxury_perfume_gift__548a5b12.jpg',
  },
];

export const products: Product[] = [
  // Watches Category
  {
    id: 'w1',
    categoryId: '1',
    nameEn: 'Heritage Automatic Chronograph',
    nameAr: 'كرونوغراف أوتوماتيك تراثي',
    descriptionEn: 'A masterpiece of Swiss horological engineering featuring a 42mm rose gold case with sapphire crystal display back. The automatic chronograph movement boasts a 72-hour power reserve and precision timing. Hand-finished dial with sunburst pattern and luminous hands ensure exceptional readability. Water-resistant to 100 meters, complete with genuine alligator leather strap.',
    descriptionAr: 'تحفة فنية من الهندسة الساعاتية السويسرية تتميز بعلبة ذهب وردي مقاس 42 ملم مع ظهر من الكريستال الياقوتي. حركة كرونوغراف أوتوماتيكية باحتياطي طاقة 72 ساعة ودقة توقيت استثنائية. قرص منتهي بعناية بنمط أشعة شمسية وعقارب مضيئة تضمن وضوحاً ممتازاً. مقاومة للماء حتى 100 متر، مع حزام جلد تمساح أصلي.',
    price: '2899.00',
    currency: 'USD',
    images: [
      '/images/luxury_gold_watch_on_f521e06a.jpg',
      '/images/luxury_gold_watch_on_173d21b2.jpg',
      '/images/luxury_gold_watch_on_8dadeeca.jpg',
    ],
    featured: 1,
    slug: 'heritage-automatic-chronograph',
  },
  {
    id: 'w2',
    categoryId: '1',
    nameEn: 'Diamond Bezel Ladies Watch',
    nameAr: 'ساعة نسائية بإطار ماسي',
    descriptionEn: 'Exquisite ladies timepiece adorned with 48 hand-set brilliant-cut diamonds on the bezel. Mother-of-pearl dial with diamond hour markers creates a mesmerizing visual effect. Swiss quartz movement ensures accuracy. 316L stainless steel case with scratch-resistant sapphire crystal. Presented with an elegant bracelet design.',
    descriptionAr: 'ساعة نسائية رائعة مزينة بـ 48 ماسة مقطوعة ببراعة على الإطار. قرص من عرق اللؤلؤ مع علامات ساعات ماسية يخلق تأثيراً بصرياً ساحراً. حركة كوارتز سويسرية تضمن الدقة. علبة من الفولاذ المقاوم للصدأ 316L مع كريستال ياقوتي مقاوم للخدش. مع تصميم سوار أنيق.',
    price: '4299.00',
    currency: 'USD',
    images: [
      '/images/luxury_gold_watch_on_173d21b2.jpg',
      '/images/luxury_gold_watch_on_f521e06a.jpg',
    ],
    featured: 1,
    slug: 'diamond-bezel-ladies-watch',
  },
  {
    id: 'w3',
    categoryId: '1',
    nameEn: 'Racing Chronograph Limited Edition',
    nameAr: 'كرونوغراف السباقات - إصدار محدود',
    descriptionEn: 'Inspired by motorsport heritage, this limited edition chronograph features a 44mm titanium case with ceramic bezel. Column-wheel chronograph mechanism provides split-second precision. Tachymeter scale for speed calculations. Anti-reflective curved sapphire crystal and rubber strap with deployment clasp. Limited to 500 pieces worldwide.',
    descriptionAr: 'مستوحاة من تراث رياضة السيارات، هذه الكرونوغراف إصدار محدود بعلبة تيتانيوم مقاس 44 ملم مع إطار سيراميك. آلية كرونوغراف عمود عجلة توفر دقة جزء من الثانية. مقياس سرعة لحسابات السرعة. كريستال ياقوتي منحني مضاد للانعكاس وحزام مطاط بمشبك انتشار. محدودة بـ 500 قطعة عالمياً.',
    price: '5499.00',
    currency: 'USD',
    images: [
      '/images/luxury_gold_watch_on_8dadeeca.jpg',
      '/images/luxury_gold_watch_on_173d21b2.jpg',
    ],
    featured: 0,
    slug: 'racing-chronograph-limited',
  },
  {
    id: 'w4',
    categoryId: '1',
    nameEn: 'Dress Watch Classic Collection',
    nameAr: 'ساعة كلاسيكية - المجموعة الأنيقة',
    descriptionEn: 'Timeless elegance in a slim 38mm profile. Gold-plated case with minimalist dial design featuring slender hour markers and hands. Premium automatic movement visible through exhibition caseback. Genuine crocodile leather strap with gold buckle. Perfect for formal occasions and professional settings.',
    descriptionAr: 'أناقة خالدة بتصميم نحيف 38 ملم. علبة مطلية بالذهب مع قرص بسيط يتميز بعلامات ساعات وعقارب رفيعة. حركة أوتوماتيكية فاخرة مرئية من خلال ظهر العرض. حزام جلد تمساح أصلي بإبزيم ذهبي. مثالية للمناسبات الرسمية والإعدادات المهنية.',
    price: '1899.00',
    currency: 'USD',
    images: [
      '/images/luxury_gold_watch_on_f521e06a.jpg',
      '/images/luxury_gold_watch_on_8dadeeca.jpg',
    ],
    featured: 0,
    slug: 'dress-watch-classic',
  },
  {
    id: 'w5',
    categoryId: '1',
    nameEn: 'Diver Professional 300M',
    nameAr: 'ساعة غوص احترافية 300 متر',
    descriptionEn: 'Professional dive watch certified to 300 meters. Unidirectional rotating bezel with luminescent markers. Helium escape valve for saturation diving. Automatic movement with date function and hacking seconds. Stainless steel bracelet with diving extension. ISO 6425 compliant.',
    descriptionAr: 'ساعة غوص احترافية معتمدة حتى 300 متر. إطار دوار أحادي الاتجاه مع علامات مضيئة. صمام إطلاق الهيليوم للغوص المشبع. حركة أوتوماتيكية مع وظيفة التاريخ وإيقاف الثواني. سوار من الفولاذ المقاوم للصدأ مع امتداد الغوص. متوافقة مع ISO 6425.',
    price: '3299.00',
    currency: 'USD',
    images: [
      '/images/luxury_gold_watch_on_173d21b2.jpg',
      '/images/luxury_gold_watch_on_8dadeeca.jpg',
    ],
    featured: 0,
    slug: 'diver-professional-300m',
  },

  // Accessories Category
  {
    id: 'a1',
    categoryId: '2',
    nameEn: 'Solitaire Diamond Pendant',
    nameAr: 'قلادة ألماس منفرد',
    descriptionEn: 'Breathtaking 1.5-carat round brilliant diamond set in 18K white gold. GIA certified with excellent cut, VS1 clarity, and F color grade. Four-prong setting allows maximum light reflection. Includes 18-inch adjustable white gold chain. Comes with authenticity certificate and luxury presentation box.',
    descriptionAr: 'ألماس دائري رائع 1.5 قيراط مرصع في ذهب أبيض عيار 18. معتمد من GIA بقطع ممتاز، نقاء VS1، ودرجة لون F. تركيب بأربعة شوكات يسمح بأقصى انعكاس للضوء. يشمل سلسلة ذهب أبيض قابلة للتعديل 18 بوصة. مع شهادة أصالة وصندوق عرض فاخر.',
    price: '6799.00',
    currency: 'USD',
    images: [
      '/images/elegant_jewelry_acce_2b234ecd.jpg',
      '/images/elegant_jewelry_acce_ab2c1b10.jpg',
    ],
    featured: 1,
    slug: 'solitaire-diamond-pendant',
  },
  {
    id: 'a2',
    categoryId: '2',
    nameEn: 'South Sea Pearl Earrings',
    nameAr: 'أقراط لؤلؤ بحر الجنوب',
    descriptionEn: 'Exceptional 12mm South Sea pearl studs with natural luster and minimal blemishes. AAA grade white pearls with rose overtones. Set in 18K yellow gold with secure push-back closures. Each pearl individually matched for size and quality. Perfect for both daytime elegance and evening sophistication.',
    descriptionAr: 'أقراط لؤلؤ بحر الجنوب استثنائية مقاس 12 ملم بلمعان طبيعي وعيوب قليلة. لؤلؤ أبيض درجة AAA مع نغمات وردية. مرصع في ذهب أصفر عيار 18 مع إغلاق آمن. كل لؤلؤة مطابقة بشكل فردي للحجم والجودة. مثالية لأناقة النهار والرقي المسائي.',
    price: '2499.00',
    currency: 'USD',
    images: [
      '/images/elegant_jewelry_acce_ab2c1b10.jpg',
      '/images/elegant_jewelry_acce_74bb331e.jpg',
    ],
    featured: 1,
    slug: 'south-sea-pearl-earrings',
  },
  {
    id: 'a3',
    categoryId: '2',
    nameEn: 'Tennis Bracelet',
    nameAr: 'سوار التنس',
    descriptionEn: 'Classic tennis bracelet featuring 50 round brilliant diamonds totaling 5 carats. Each stone carefully selected and individually set in platinum. Uniform appearance with secure box clasp and safety latch. 7-inch length, suitable for most wrist sizes. Timeless design that never goes out of style.',
    descriptionAr: 'سوار تنس كلاسيكي يضم 50 ماسة دائرية بإجمالي 5 قيراط. كل حجر مختار بعناية ومرصع بشكل فردي في البلاتين. مظهر موحد مع قفل صندوق آمن ومزلاج أمان. طول 7 بوصات، مناسب لمعظم أحجام المعصم. تصميم خالد لا يخرج عن الموضة أبداً.',
    price: '8999.00',
    currency: 'USD',
    images: [
      '/images/elegant_jewelry_acce_74bb331e.jpg',
      '/images/elegant_jewelry_acce_2b234ecd.jpg',
    ],
    featured: 0,
    slug: 'tennis-bracelet',
  },
  {
    id: 'a4',
    categoryId: '2',
    nameEn: 'Eternity Band Ring',
    nameAr: 'خاتم الأبدية',
    descriptionEn: 'Stunning eternity band with continuous row of princess-cut diamonds. 2.5 total carat weight set in 14K white gold. Each diamond precision-cut and perfectly matched. Comfort-fit band design for all-day wear. Available in multiple sizes. Symbolizes eternal love and commitment.',
    descriptionAr: 'خاتم أبدية مذهل مع صف مستمر من الماس بقطع أميرة. وزن إجمالي 2.5 قيراط مرصع في ذهب أبيض عيار 14. كل ماسة مقطوعة بدقة ومطابقة تماماً. تصميم حزام مريح للارتداء طوال اليوم. متوفر بأحجام متعددة. يرمز إلى الحب والالتزام الأبدي.',
    price: '3899.00',
    currency: 'USD',
    images: [
      '/images/elegant_jewelry_acce_2b234ecd.jpg',
      '/images/elegant_jewelry_acce_ab2c1b10.jpg',
    ],
    featured: 0,
    slug: 'eternity-band-ring',
  },
  {
    id: 'a5',
    categoryId: '2',
    nameEn: 'Gemstone Statement Necklace',
    nameAr: 'قلادة أحجار كريمة مميزة',
    descriptionEn: 'Magnificent multi-strand necklace featuring emeralds, rubies, and sapphires. Natural gemstones totaling 30 carats in alternating pattern. 18K yellow gold setting with secure lobster clasp. Adjustable length from 16 to 18 inches. Makes a bold statement for special occasions.',
    descriptionAr: 'قلادة متعددة الخيوط رائعة تتميز بالزمرد والياقوت والياقوت الأزرق. أحجار كريمة طبيعية بإجمالي 30 قيراط بنمط متناوب. تركيب ذهب أصفر عيار 18 مع مشبك جراد البحر آمن. طول قابل للتعديل من 16 إلى 18 بوصة. تقدم بياناً جريئاً للمناسبات الخاصة.',
    price: '12499.00',
    currency: 'USD',
    images: [
      '/images/elegant_jewelry_acce_ab2c1b10.jpg',
      '/images/elegant_jewelry_acce_74bb331e.jpg',
    ],
    featured: 0,
    slug: 'gemstone-statement-necklace',
  },
  {
    id: 'a6',
    categoryId: '2',
    nameEn: 'Cufflinks Gold Set',
    nameAr: 'طقم أزرار أكمام ذهبية',
    descriptionEn: 'Sophisticated 18K gold cufflinks with intricate engraved details. Octagonal shape with polished and brushed finish combination. Secure toggle back closure. Presented in premium leather case. Perfect gift for the distinguished gentleman.',
    descriptionAr: 'أزرار أكمام أنيقة من الذهب عيار 18 مع تفاصيل محفورة معقدة. شكل ثماني مع تشطيب مصقول ومصقول بالفرشاة. إغلاق خلفي آمن. مقدم في علبة جلدية فاخرة. هدية مثالية للرجل المميز.',
    price: '1599.00',
    currency: 'USD',
    images: [
      '/images/elegant_jewelry_acce_74bb331e.jpg',
      '/images/elegant_jewelry_acce_2b234ecd.jpg',
    ],
    featured: 0,
    slug: 'cufflinks-gold-set',
  },

  // Makeup Category
  {
    id: 'm1',
    categoryId: '3',
    nameEn: 'Prestige Lipstick Collection',
    nameAr: 'مجموعة أحمر شفاه بريستيج',
    descriptionEn: 'Luxurious set of 6 richly pigmented lipsticks in curated shades from nude to deep burgundy. Infused with hyaluronic acid and vitamin E for 8-hour hydration. Creamy texture with semi-matte finish. Refillable gold-plated cases reduce environmental impact. Dermatologist-tested and paraben-free formula.',
    descriptionAr: 'طقم فاخر من 6 أحمر شفاه غني بالصبغة بدرجات منتقاة من اللون الطبيعي إلى العنابي الداكن. مدعم بحمض الهيالورونيك وفيتامين E للترطيب لمدة 8 ساعات. قوام كريمي بتشطيب شبه مطفي. علب مطلية بالذهب قابلة لإعادة التعبئة تقلل التأثير البيئي. تركيبة مختبرة من قبل أطباء الجلد وخالية من البارابين.',
    price: '289.00',
    currency: 'USD',
    images: [
      '/images/luxury_makeup_cosmet_ef2662b8.jpg',
      '/images/luxury_makeup_cosmet_435574f1.jpg',
    ],
    featured: 1,
    slug: 'prestige-lipstick-collection',
  },
  {
    id: 'm2',
    categoryId: '3',
    nameEn: 'Ultimate Eyeshadow Palette',
    nameAr: 'لوحة ظلال عيون نهائية',
    descriptionEn: '20-shade professional eyeshadow palette with buttery smooth application. Features matte, shimmer, metallic, and duo-chrome finishes. Highly pigmented formula buildable from sheer to intense. Includes large mirror and dual-ended application brush. Cruelty-free and vegan formulation.',
    descriptionAr: 'لوحة ظلال عيون احترافية بـ 20 درجة بتطبيق ناعم كالزبدة. تتميز بتشطيبات مطفية، لامعة، معدنية، وثنائية اللون. تركيبة عالية الصبغة قابلة للبناء من الشفاف إلى الكثيف. تشمل مرآة كبيرة وفرشاة تطبيق مزدوجة الطرف. تركيبة خالية من القسوة ونباتية.',
    price: '149.00',
    currency: 'USD',
    images: [
      '/images/luxury_makeup_cosmet_435574f1.jpg',
      '/images/luxury_makeup_cosmet_38f4e6ef.jpg',
    ],
    featured: 1,
    slug: 'ultimate-eyeshadow-palette',
  },
  {
    id: 'm3',
    categoryId: '3',
    nameEn: 'Professional Brush Collection',
    nameAr: 'مجموعة فرش احترافية',
    descriptionEn: 'Complete 15-piece brush set crafted with premium synthetic and natural bristles. Includes face, eye, and lip brushes with ergonomic rose gold handles. Each brush designed for specific application technique. Comes with luxury vegan leather case and brush cleaning mat. Professional quality for flawless makeup application.',
    descriptionAr: 'طقم فرش كامل من 15 قطعة مصنوع من شعيرات صناعية وطبيعية فاخرة. يشمل فرش الوجه والعين والشفاه مع مقابض ذهبية وردية مريحة. كل فرشاة مصممة لتقنية تطبيق محددة. يأتي مع علبة جلدية نباتية فاخرة وحصيرة تنظيف الفرش. جودة احترافية لتطبيق مكياج لا تشوبه شائبة.',
    price: '349.00',
    currency: 'USD',
    images: [
      '/images/luxury_makeup_cosmet_38f4e6ef.jpg',
      '/images/luxury_makeup_cosmet_ef2662b8.jpg',
    ],
    featured: 0,
    slug: 'professional-brush-collection',
  },
  {
    id: 'm4',
    categoryId: '3',
    nameEn: 'Luminous Foundation Duo',
    nameAr: 'ثنائي كريم الأساس المضيء',
    descriptionEn: 'Innovative dual-formula foundation providing buildable medium to full coverage. Lightweight serum-infused formula with SPF 30 protection. Contains peptides and antioxidants for skin-care benefits. Available in 40 shades for perfect color matching. Long-lasting 16-hour wear with radiant finish.',
    descriptionAr: 'كريم أساس مبتكر بتركيبة مزدوجة يوفر تغطية متوسطة إلى كاملة قابلة للبناء. تركيبة خفيفة الوزن مدعمة بالمصل مع حماية SPF 30. يحتوي على الببتيدات ومضادات الأكسدة لفوائد العناية بالبشرة. متوفر بـ 40 درجة لمطابقة اللون المثالية. ارتداء طويل الأمد 16 ساعة بتشطيب مشرق.',
    price: '189.00',
    currency: 'USD',
    images: [
      '/images/luxury_makeup_cosmet_ef2662b8.jpg',
      '/images/luxury_makeup_cosmet_435574f1.jpg',
    ],
    featured: 0,
    slug: 'luminous-foundation-duo',
  },
  {
    id: 'm5',
    categoryId: '3',
    nameEn: 'Luxury Skincare-Makeup Hybrid Set',
    nameAr: 'طقم هجين فاخر للعناية بالبشرة والمكياج',
    descriptionEn: 'Revolutionary 4-piece set combining skincare benefits with makeup performance. Includes primer with retinol, tinted moisturizer with ceramides, setting spray with niacinamide, and overnight treatment balm. Clinical results show improved skin texture after 4 weeks. Award-winning formulations.',
    descriptionAr: 'طقم ثوري من 4 قطع يجمع بين فوائد العناية بالبشرة وأداء المكياج. يشمل برايمر مع الريتينول، مرطب ملون مع السيراميد، رذاذ تثبيت مع النياسيناميد، وبلسم علاج ليلي. تظهر النتائج السريرية تحسناً في نسيج البشرة بعد 4 أسابيع. تركيبات حائزة على جوائز.',
    price: '269.00',
    currency: 'USD',
    images: [
      '/images/luxury_makeup_cosmet_38f4e6ef.jpg',
      '/images/luxury_makeup_cosmet_435574f1.jpg',
    ],
    featured: 0,
    slug: 'skincare-makeup-hybrid-set',
  },

  // Gifts Category
  {
    id: 'g1',
    categoryId: '4',
    nameEn: 'Signature Parfum Collection',
    nameAr: 'مجموعة عطور السيجنتشر',
    descriptionEn: 'Exclusive parfum set featuring our three signature scents in 50ml bottles. Oriental Oud with rich amber and sandalwood notes, Floral Bloom with jasmine and rose essence, and Citrus Fresh with bergamot and neroli. Presented in luxurious gift box with silk lining. Each fragrance crafted by renowned perfumers.',
    descriptionAr: 'طقم عطور حصري يضم ثلاثة عطور مميزة في زجاجات 50 مل. عود شرقي بنفحات العنبر الغنية وخشب الصندل، زهور متفتحة مع جوهر الياسمين والورد، وحمضيات منعشة مع البرغموت والنيرولي. مقدم في صندوق هدايا فاخر مع بطانة حريرية. كل عطر صُنع من قبل عطارين مشهورين.',
    price: '599.00',
    currency: 'USD',
    images: [
      '/images/luxury_perfume_gift__548a5b12.jpg',
      '/images/luxury_perfume_gift__aa85a4a9.jpg',
    ],
    featured: 1,
    slug: 'signature-parfum-collection',
  },
  {
    id: 'g2',
    categoryId: '4',
    nameEn: 'Limited Edition Eau de Parfum',
    nameAr: 'عطر محدود الإصدار',
    descriptionEn: 'Rare limited edition eau de parfum in handcrafted Baccarat crystal bottle. Complex fragrance pyramid featuring top notes of saffron and cardamom, heart notes of iris and violet, base notes of leather and vetiver. Only 1000 bottles produced worldwide. Includes numbered certificate of authenticity.',
    descriptionAr: 'عطر محدود الإصدار نادر في زجاجة كريستال باكارا مصنوعة يدوياً. هرم عطري معقد يضم نفحات عليا من الزعفران والهيل، نفحات قلبية من القزحية والبنفسج، نفحات قاعدية من الجلد والفيتيفر. تم إنتاج 1000 زجاجة فقط عالمياً. يشمل شهادة أصالة مرقمة.',
    price: '899.00',
    currency: 'USD',
    images: [
      '/images/luxury_perfume_gift__aa85a4a9.jpg',
      '/images/luxury_perfume_gift__94fbf062.jpg',
    ],
    featured: 1,
    slug: 'limited-edition-eau-de-parfum',
  },
  {
    id: 'g3',
    categoryId: '4',
    nameEn: 'Travel Fragrance Wardrobe',
    nameAr: 'خزانة عطور السفر',
    descriptionEn: 'Sophisticated travel set with 5 miniature parfums (10ml each) in refillable atomizers. Includes day and night scents plus seasonal fragrances. Compact leather case fits easily in carry-on luggage. Perfect for fragrance enthusiasts who travel frequently. TSA-compliant sizes.',
    descriptionAr: 'طقم سفر أنيق مع 5 عطور صغيرة (10 مل لكل منها) في رشاشات قابلة لإعادة التعبئة. يشمل روائح النهار والليل بالإضافة إلى عطور موسمية. علبة جلدية مدمجة تناسب بسهولة في أمتعة الحمل. مثالية لعشاق العطور الذين يسافرون بشكل متكرر. أحجام متوافقة مع TSA.',
    price: '279.00',
    currency: 'USD',
    images: [
      '/images/luxury_perfume_gift__94fbf062.jpg',
      '/images/luxury_perfume_gift__548a5b12.jpg',
    ],
    featured: 0,
    slug: 'travel-fragrance-wardrobe',
  },
  {
    id: 'g4',
    categoryId: '4',
    nameEn: 'Artisan Perfume Discovery Set',
    nameAr: 'طقم اكتشاف العطور الحرفية',
    descriptionEn: 'Curated collection of 8 artisan fragrances (5ml each) from boutique perfume houses. Explore unique scent profiles including woody, aquatic, gourmand, and spicy families. Includes detailed scent cards and perfumer notes. Elegant presentation box perfect for gifting. Discover your new signature scent.',
    descriptionAr: 'مجموعة منتقاة من 8 عطور حرفية (5 مل لكل منها) من دور عطور بوتيك. استكشف ملفات رائحة فريدة بما في ذلك العائلات الخشبية والمائية والشره والحارة. يشمل بطاقات رائحة مفصلة وملاحظات العطار. صندوق عرض أنيق مثالي للإهداء. اكتشف عطرك المميز الجديد.',
    price: '199.00',
    currency: 'USD',
    images: [
      '/images/luxury_perfume_gift__548a5b12.jpg',
      '/images/luxury_perfume_gift__aa85a4a9.jpg',
    ],
    featured: 0,
    slug: 'artisan-perfume-discovery-set',
  },
  {
    id: 'g5',
    categoryId: '4',
    nameEn: 'Luxury Bath & Fragrance Gift Set',
    nameAr: 'طقم هدايا فاخر للحمام والعطور',
    descriptionEn: 'Complete luxury bathing experience with matching fragrance. Includes body wash, body lotion, bath oil, scented candle, and 30ml eau de parfum. Enriched with shea butter and essential oils. Beautifully packaged in presentation box with ribbon. Perfect for special occasions and self-care.',
    descriptionAr: 'تجربة استحمام فاخرة كاملة مع عطر متطابق. يشمل غسول الجسم، لوشن الجسم، زيت الاستحمام، شمعة معطرة، و30 مل عطر. مدعم بزبدة الشيا والزيوت الأساسية. مغلف بشكل جميل في صندوق عرض مع شريط. مثالي للمناسبات الخاصة والعناية الذاتية.',
    price: '349.00',
    currency: 'USD',
    images: [
      '/images/luxury_perfume_gift__aa85a4a9.jpg',
      '/images/luxury_perfume_gift__94fbf062.jpg',
    ],
    featured: 0,
    slug: 'luxury-bath-fragrance-set',
  },
];
